### ISSUE TITLE
Pcap Imported not working with Burp Suite 1.6.20

### ISSUE THREAD

**Issue by robgas** [nccgroup/pcap-burp#6]
Hi,

I'm trying the extension from the BApp Store or with the manual import (version burp-pcap-20150319.jar) but The "Open Pcap File..." is not available under the Scanner and Target tabs.

I've tried the extension with Burp Suite 1.6.08 and it works.

**Comment by neonbunny** [comment]
Hi,

I suspect this is a result of the updated Burp GUI which merges elements from the Scanner and Target tabs. You should be able to find the option under the right click menu on the "Issues" section of the Target tab, or alternatively on the right click menu of the Target tree display (but only when there's some other content in the Target tree, from the proxy for example).

If you still can't find the menu, please let me know.

**Comment by neonbunny** [comment]
Updated the readme and made the plugin appear in a few more menus. Considering this closed.
